# Generated by Django 4.2.4 on 2023-08-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
